[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
rand = "0.9.0"
tokio = {version = "1.44.2", features = ["full"]}
tokio-tungstenite = "0.26.2"
url = "2.5.4"
